name: Fuzz Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzztest:
    name: Fuzz Test
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_fuzztest
      BUILD_TYPE: RelWithDebug

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure
        run: |
          mkdir "$BUILD_DIR"
          cmake                               \
            -S .                              \
            -B "$BUILD_DIR"                   \
            -G Ninja                          \
            -D CMAKE_BUILD_TYPE="$BUILD_TYPE" \
            -D CMAKE_CXX_COMPILER="clang++"   \
            -D CMAKE_C_COMPILER="clang"       \
            -D MCODED7_FUZZTEST=Yes

      - name: Build
        run: |
          cmake --build "$BUILD_DIR" --config "$BUILD_TYPE" --verbose

      - name: Fuzz
        run: |
          "$BUILD_DIR/unittests" --fuzz_for 30s
